// @ts-nocheck
import { loginSchoolPayload } from './login_input';
const root=document.querySelector('#app-root'); const view=document.body.dataset.view||'activities';
const el=(t,o={},c=[])=>{const n=document.createElement(t); if(o.text!=null)n.textContent=o.text; for(const[k,v]of Object.entries(o)){if(k!=='text') n[k]!==undefined?(n[k]=v):n.setAttribute(k,String(v));} c.forEach(x=>n.append(x instanceof Node?x:document.createTextNode(String(x)))); return n;};
async function requestJSON(u,o={}){const r=await fetch(u,o); if(r.ok)return r.status===204?null:r.json(); const text=await r.text(); try{const data=JSON.parse(text);throw Error(data?.error?.message||r.statusText)}catch(e){if(e instanceof SyntaxError)throw Error(text||r.statusText);throw e}}
function textCell(v){ return el('td',{text:v??'-'}); } const cell=textCell;
const table=(h,rs,caption='')=>el('div',{className:'table-wrap'},[caption&&el('small',{text:'表格可横向滚动'}),el('table',{},[caption&&el('caption',{text:caption}),el('thead',{},[el('tr',{},h.map(x=>el('th',{text:x,scope:'col'})))]),el('tbody',{},rs.map(r=>el('tr',{},r)))])]);
const CREDIT_KEY='pu.credit.v2', BLOCKS=['校园阅读','创新创业类','志愿服务','思想引领','学术讲座','社会实践','体育健康','美育素养','劳动教育','职业发展','团队活动','科技竞赛','其他'], HARD=new Set(BLOCKS.slice(0,5)), TYPE_BLOCK={'志愿公益':'志愿服务','创新创业':'创新创业类','思想引领':'思想引领','校园阅读':'校园阅读','学术讲座':'学术讲座'};
function loadCredit(){try{const d=JSON.parse(localStorage.getItem(CREDIT_KEY));if(d?.version===2&&Number.isInteger(d.stage)&&d.credits)return d}catch{}return {version:2,stage:1,credits:{}}} function saveCredit(d){localStorage.setItem(CREDIT_KEY,JSON.stringify(d))}
const activityCredit=a=>Math.max(0,...(a.score_items||[]).filter(x=>x.kind==='academic_credit').map(x=>Math.max(0,Number(x.value)||0)));
const _safeActivityId=activity=>encodeURIComponent(activity.activity_id);
function renderCredit(){const d=loadCredit(), total=Object.values(d.credits).reduce((a,b)=>a+b,0); const rows=BLOCKS.map(b=>{const got=d.credits[b]||0,t=HARD.has(b)?1:0; const inp=el('input',{type:'number',min:'0',step:'.1',value:got,ariaLabel:`${b}已获`}); inp.oninput=()=>{d.credits[b]=Math.max(0,Number(inp.value)||0);saveCredit(d);renderCredit()}; return [textCell(b),el('td',{},[inp]),textCell(t),textCell(got>=t?'已达':'进行中')]}); const stage=el('select',{ariaLabel:'当前阶段'},[1,2,3,4,5,6].map(i=>el('option',{value:i,text:`阶段 ${i}`,selected:i===d.stage}))); stage.onchange=()=>{d.stage=+stage.value;saveCredit(d);renderCredit()}; root.replaceChildren(el('h1',{text:'学分进度'}),el('div',{className:'credit-dashboard'},[el('div',{className:'summary-card'},[el('strong',{text:`合计 ${total} / 6`}),el('span',{className:'badge',text:`阶段缺口 ${Math.max(0,d.stage-total)}`}),stage]),el('p',{className:'notice',text:'已报名活动不计入；讲座学分需核实'})]),table(['板块','已获','目标','状态'],rows,'学分板块'),el('button',{text:'重置',onclick:()=>{localStorage.removeItem(CREDIT_KEY);renderCredit()}}));}
function gapInfo(a,d){const b=TYPE_BLOCK[a.activity_type]||'其他', gap=Math.max(0,(HARD.has(b)?1:0)-(d.credits[b]||0)), c=activityCredit(a); const priority=gap>0&&c>=(a.activity_type==='学术讲座'?.5:0.01)?1:0; return {b,gap,c,priority};}
async function renderActivities(){const a=await requestJSON('/api/activities'),d=loadCredit(); const sel=el('select',{ariaLabel:'奖励类型'},['','academic_credit','credit','point'].map(v=>el('option',{value:v,text:v||'奖励类型'}))),sort=el('select',{ariaLabel:'排序'},['','signup_end_time','academic_credit','credit','point','gap_recommend'].map(v=>el('option',{value:v,text:v||'排序'}))),box=el('div'); const draw=()=>{let x=a.filter(i=>!sel.value||(i.score_items||[]).some(z=>z.kind===sel.value)); if(sort.value==='signup_end_time')x.sort((u,v)=>String(u.signup_end_time||'').localeCompare(String(v.signup_end_time||''))); if(sort.value==='academic_credit')x.sort((u,v)=>activityCredit(v)-activityCredit(u)); if(sort.value==='credit'||sort.value==='point')x.sort((u,v)=>(Math.max(0,...(v.score_items||[]).filter(z=>z.kind===sort.value).map(z=>Number(z.value)||0)))-(Math.max(0,...(u.score_items||[]).filter(z=>z.kind===sort.value).map(z=>Number(z.value)||0)))); if(sort.value==='gap_recommend')x.sort((u,v)=>{const U=gapInfo(u,d),V=gapInfo(v,d); return V.priority-U.priority||V.gap-U.gap||V.c-U.c||String(u.signup_end_time||'').localeCompare(String(v.signup_end_time||''))}); box.replaceChildren(table(['ID','标题','类型','报名窗口','奖励','推荐'],x.map(i=>{const g=gapInfo(i,d); return [cell(i.activity_id),cell(i.title),cell(i.activity_type),cell(`${i.signup_start_time||'-'} ~ ${i.signup_end_time||'-'}`),cell((i.score_items||[]).map(z=>`${z.label}:${Math.max(0,Number(z.value)||0)}`).join(' / ')),cell(g.priority?'匹配缺口，建议优先':'常规活动')]})))}; sel.onchange=sort.onchange=draw; root.replaceChildren(el('h1',{text:'活动'}),el('div',{className:'filters'},[el('label',{},['奖励类型',sel]),el('label',{},['排序',sort])]),box); draw()}
async function renderActivityDetail(id){const a=await requestJSON(`/api/activities/${encodeURIComponent(id)}`); root.replaceChildren(el('h1',{text:a.title||id}),el('p',{text:`预计学分：${activityCredit(a)}`}),createPlanForm(a))} function createPlanForm(a){const f=el('form',{className:'plan-form', 'data-activity':encodeURIComponent(a.activity_id)}),runAt=el('input',{type:'datetime-local',required:true,ariaLabel:'计划时间'}); f.append(el('label',{},['计划时间',runAt]),el('button',{type:'submit',text:'创建计划'})); f.onsubmit=async e=>{e.preventDefault();await requestJSON('/api/signup/plans',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({activity_id:a.activity_id,activity_title:a.title,run_at:new Date(runAt.value).toISOString()})})}; return f}
async function renderPlans(){const ps=await requestJSON('/api/signup/plans'),msg=el('p',{ariaLive:'polite'}); root.replaceChildren(el('h1',{text:'计划'}),msg,table(['ID','活动','状态','操作'],ps.map(p=>[cell(p.plan_id),cell(p.activity_title),cell(p.status),p.status==='pending'?el('button',{text:'取消',onclick:async()=>{await requestJSON(`/api/signup/plans/${p.plan_id}`,{method:"DELETE"});msg.textContent='已取消';renderPlans()}}):cell('详情')])))}
async function renderAttempts(){const as=await requestJSON('/api/signup/attempts');root.replaceChildren(el('h1',{text:'记录'}),table(['计划','状态','消息'],as.map(a=>[cell(a.plan_id),cell(a.status),cell(a.message)])))}
async function renderSettings(){const status=await requestJSON('/api/auth/status'),msg=el('p',{ariaLive:'polite',text:status.authenticated?`已登录：${status.user||''}`:(status.message||'未登录')}),form=el('form',{className:'auth-form'}),user=el('input',{type:'text',name:'username',required:true,autocomplete:'username',ariaLabel:'用户名'}),pass=el('input',{type:'password',name:'password',required:true,autocomplete:'current-password',ariaLabel:'密码'}),school=el('input',{type:'text',name:'school',required:true,autocomplete:'off',placeholder:'学校 SID、编码 SID 或 class 登录链接',ariaLabel:'学校 SID 或 class 登录链接'}); const logout=()=>{requestJSON('/api/auth/logout',{method:'POST'}).then(()=>renderSettings())}; if(status.authenticated) form.append(el('button',{type:'button',text:'登出',onclick:logout})); else {form.append(el('label',{},['用户名',user]),el('label',{},['密码',pass]),el('label',{},['学校 SID 或 class 登录链接',school]),el('p',{className:'muted',text:'可直接粘贴完整 class 登录链接；凭据仅用于本机登录。'}),el('button',{type:'submit',text:'登录'})); form.onsubmit=async e=>{e.preventDefault();try{const schoolPayload=loginSchoolPayload(school.value);await requestJSON('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:user.value,password:pass.value,...schoolPayload})});renderSettings()}catch(err){pass.value='';msg.textContent=err.message}};} root.replaceChildren(el('h1',{text:'设置'}),msg,form)}
(async()=>{try{if(view==='settings')await renderSettings();else if(view==='credit')renderCredit();else if(view==='plans')await renderPlans();else if(view==='attempts')await renderAttempts();else if(view.startsWith('activity:'))await renderActivityDetail(view.slice(9));else await renderActivities()}catch(e){root.textContent=e.message}})();
